#!/usr/bin/python3

from __future__ import print_function

import os
import sys
import dbus
import dbus.service
import dbus.mainloop.glib
from gi.repository import GLib
import logging

'''
To enable message receiving, add to /etc/dbus-1/system.d/bluetooth.conf :
<allow send_interface="org.mpris.MediaPlayer2.Player"/>
Not needed if using system service below. 
_________________

To enable system service, add to /etc/dbus-1/system.d/ (or /usr/share/dbus-1/system.d)
the file: org.mpris.MediaPlayer2.uplay.conf

And make it effective:
systemctl reload dbus

https://dbus.freedesktop.org/doc/dbus-daemon.1.html

OR

To enable system service, add to /usr/share/dbus-1/system.conf
<policy context="default">
....
....
  <allow own="org.mpris.MediaPlayer2.uplay"/> 
_________________

Service file can be created at:
/usr/share/dbus-1/services/org.mpris.MediaPlayer2.uplay.service

[D-BUS Service]
Name=org.mpris.MediaPlayer2.uplay
Exec=/bin/false

To avoid the error:
error time=1625755110.144453 sender=org.freedesktop.DBus -> destination=:1.54 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=7831
string "The name org.mpris.MediaPlayer2.uplay was not provided by any .service files"
'''
SERVICE_NAME = "org.bluez"
MPRIS_MEDIAP_IFACE = "org.mpris.MediaPlayer2"
MPRIS_PLAYER_IFACE = "org.mpris.MediaPlayer2.Player"
MEDIA_IFACE = SERVICE_NAME + '.Media1'

ADAPTER_INTERFACE = SERVICE_NAME + ".Adapter1"

class uPlayer(dbus.service.Object):

	def __init__(self):

		self.properties = None
		self.metadata = None
		self.player_path = "/org/mpris/MediaPlayer2"

		# Session Bus should be used with mprix-proxy
		# bus = dbus.SessionBus()
		# System bus is used as mpris-proxy not always working properly (bluez v5.50)
		bus = dbus.SystemBus()
		service_name = MPRIS_MEDIAP_IFACE+'.uplay'
		bus_name = dbus.service.BusName(name=service_name, bus=bus, replace_existing=True)
		dbus.service.Object.__init__(self, object_path=self.player_path, bus_name=bus_name)

	def set_object(self, debug=False):
		
		self.track = dbus.Dictionary({
				"xesam:title" : "DBus, Magic Bus",
				"xesam:artist" : ["The Hoo"],
				"xesam:album" : "My Comunication",
				"xesam:genre" : ["Phony"],
				"xesam:trackNumber" : dbus.Int32(1),
				"mpris:length" : dbus.Int64(10000) },
				#"mpris:trackid": dbus.ObjectPath("/track/id"),
				signature="sv")

		self.properties = dbus.Dictionary({
				"PlaybackStatus" : "stopped",
				"Identity" : "SimplePlayer",
				"LoopStatus" : "None",
				#"Rate" : dbus.Double(1.0),
				"Shuffle" : dbus.Boolean(False),
				"Metadata" : self.track,
				#"Volume" : dbus.Double(1.0),
				"Position" : dbus.Int64(10),
				#"MinimumRate" : dbus.Double(1.0),
				#"MaximumRate" : dbus.Double(1.0),
				"CanGoNext" : dbus.Boolean(False),
				"CanGoPrevious" : dbus.Boolean(False),
				"CanPlay" : dbus.Boolean(True),
				"CanPause" : dbus.Boolean(True),
				#"CanSeek" : dbus.Boolean(False),
				"CanControl" : dbus.Boolean(True),
				},
				signature="sv")
			
		self.media_props = dbus.Dictionary({
				"SupportedMimeTypes" : [""],
				"SupportedUriSchemes" : [""],
				"CanQuit" : dbus.Boolean(True),
				"CanRaise" : dbus.Boolean(False),
				"HasTrackList" : dbus.Boolean(False),
				"DesktopEntry" : "uplayer",
				"Identity" : "uplayer",
				},
				signature="sv")

		if debug:
			handler = InputHandler(self)
			GLib.io_add_watch(sys.stdin, GLib.IO_IN, handler.handle)

	@dbus.service.method(MPRIS_MEDIAP_IFACE)
	def Quit(self):
		logger.info("Quit")
		sys.exit()

	@dbus.service.method(MPRIS_MEDIAP_IFACE)
	def Raise(self):
		logger.info("Raise")

	@dbus.service.method(MPRIS_PLAYER_IFACE, signature="")
	def PlayPause(self):
		if self.properties["PlaybackStatus"] is "playing":
			self.Set(MPRIS_PLAYER_IFACE, "PlaybackStatus","paused")
		else:
			self.Set(MPRIS_PLAYER_IFACE, "PlaybackStatus","playing")		
		logger.info("Status: %s ", self.properties["PlaybackStatus"])
		logger.debug("Title: %s", self.properties["Metadata"]["xesam:title"])

	@dbus.service.method(MPRIS_PLAYER_IFACE, signature="")
	def Pause(self):
		self.PlayPause()
	
	@dbus.service.method(MPRIS_PLAYER_IFACE, signature="")
	def Play(self):
		self.PlayPause()

	@dbus.service.signal(dbus.PROPERTIES_IFACE,
							signature="sa{sv}as")
	def PropertiesChanged(self, interface, properties,
						invalidated = dbus.Array()):
		"""PropertiesChanged(interface, properties, invalidated)

		Send a PropertiesChanged signal. 'properties' is a dictionary
		containing string parameters as specified in doc/media-api.txt.
		"""
		logger.debug ("Properties changed on interface: "+str(interface))

	
	@dbus.service.method(dbus.PROPERTIES_IFACE,	in_signature="ssv")
	def Set(self, interface, prop, value):
		# validate the property name and value, update internal state
		self.properties[prop] = value
		self.PropertiesChanged(interface,
            { prop: value }, [])
		logger.debug("Set (%s, %s)", prop, value)

	@dbus.service.method(dbus.PROPERTIES_IFACE,	in_signature="ss", out_signature="v")
	def Get(self, interface, prop):
		logger.info("Get: "+str(prop))
		return self.properties[prop]

	@dbus.service.method(dbus.PROPERTIES_IFACE,	in_signature="s", out_signature="a{sv}", 
					sender_keyword='sender' )
	def GetAll(self, interface, sender=None ):
		logger.debug("GetAll on interface: %s sender: %s", interface, sender)
		if interface == MPRIS_PLAYER_IFACE:
			return self.properties
		if interface == MPRIS_MEDIAP_IFACE:
			# org.mpris.MediaPlayer2 properties not implemented
			return self.media_props

class InputHandler:
	def __init__(self, player):
		self.player = player

		logger.debug("Use python syntax to pass arguments to available methods.\n" \
        "E.g.: PropertiesChanged(MPRIS_PLAYER_IFACE, {'PlaybackStatus':'stopped'}, [])")
		self.prompt()

	def prompt(self):
		logger.debug('>>> ')
		sys.stdout.flush()

	def handle(self, fd):
		s = os.read(fd.fileno(), 1024).strip().decode("utf-8")
		try:
			cmd = s[:s.find('(')]
		except ValueError:
			logger.error("Malformed command")
			return True

		try:
			exec ("self.player.%s" % s)
		except Exception as e:
			logger.error(e)
			pass
		self.prompt()
		return True

def get_managed_objects():
	bus = dbus.SystemBus()
	manager = dbus.Interface(bus.get_object("org.bluez", "/"),
				"org.freedesktop.DBus.ObjectManager")
	return manager.GetManagedObjects()

def find_adapter(pattern=None):
	return find_adapter_in_objects(get_managed_objects(), pattern)

def find_adapter_in_objects(objects, pattern=None):
	bus = dbus.SystemBus()
	for path, ifaces in objects.items():
		adapter = ifaces.get(ADAPTER_INTERFACE)

		if adapter is None:
			continue

		if not pattern or pattern == adapter["Address"] or \
							path.endswith(pattern):
			obj = bus.get_object(SERVICE_NAME, path)
			return dbus.Interface(obj, ADAPTER_INTERFACE)
	raise Exception("Bluetooth adapter not found")

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
	
	logging.basicConfig(format='%(levelname)s: %(message)s')
	logger = logging.getLogger(__name__)
	logger.setLevel(logging.INFO)
	logger.info("Starting uplay MPRIS Player")

	uplay_player = uPlayer()

	adapter_path = find_adapter().object_path
	logger.debug("adapter_path = %s", adapter_path)

	uplay_player.set_object()

	logger.debug('Registering media player')
	logger.debug('Properties: %s', uplay_player.properties)	
	system_bus = dbus.SystemBus()
	media = dbus.Interface(system_bus.get_object(SERVICE_NAME, adapter_path),
						MEDIA_IFACE)

	media.RegisterPlayer(dbus.ObjectPath(uplay_player.player_path), uplay_player.properties)

	mainloop = GLib.MainLoop()
	mainloop.run()
